# FUNCIONES MAS COMUNES EN NUMPY

In [1]:
import numpy as np

# SHAPE Y RESHAPE

In [3]:
arr = np.random.randint(1,10,(3,2))
arr

array([[9, 7],
       [9, 2],
       [8, 1]])

In [4]:
arr.shape

(3, 2)

In [5]:
arr.ndim

2

In [6]:
arr.reshape(1,6)

array([[9, 7, 9, 2, 8, 1]])

# MAX Y ARGMAX

In [20]:
arr = np.random.randint(1,20,10)
arr

array([ 4, 15, 15,  4,  9, 11, 19,  8,  1, 19])

In [21]:
matriz = arr.reshape(2,5)
matriz

array([[ 4, 15, 15,  4,  9],
       [11, 19,  8,  1, 19]])

In [22]:
arr.max()

np.int64(19)

In [23]:
matriz.max()

np.int64(19)

In [25]:
arr.argmax()

np.int64(6)

In [26]:
matriz.argmax()

np.int64(6)

# MIN Y ARGMIN

In [27]:
arr.min()

np.int64(1)

In [28]:
matriz.min()

np.int64(1)

In [30]:
matriz.min(0)

array([ 4, 15,  8,  1,  9])

In [31]:
matriz.min(1)

array([4, 1])

# SORT

In [32]:
arr

array([ 4, 15, 15,  4,  9, 11, 19,  8,  1, 19])

In [33]:
arr.sort()
arr

array([ 1,  4,  4,  8,  9, 11, 15, 15, 19, 19])

In [34]:
arr2 = arr[::-1]
arr2

array([19, 19, 15, 15, 11,  9,  8,  4,  4,  1])